function apiBase() {
	if (window.INCIDENTS_API) return window.INCIDENTS_API;
	if (window.location.port === "8000" || window.location.pathname.startsWith("/app")) {
		return `${window.location.origin}/api`;
	}
	if (window.location.hostname === "localhost" || window.location.hostname === "127.0.0.1") {
		return `${window.location.protocol}//${window.location.hostname}:8000/api`;
	}
	const apiHost = window.location.hostname.replace(/-5500(?=\.)/, "-8000");
	return `${window.location.protocol}//${apiHost}/api`;
}
const API = apiBase();
const BRANCHES = ["central", "medellin_poblado", "medellin_laureles", "medellin_envigado", "medellin_sabaneta", "medellin_belen", "medellin_las_americas", "medellin_mayorca", "florida_miami", "florida_orlando", "florida_tampa", "florida_fort_lauderdale", "florida_boca_raton", "florida_weston", "florida_doral"];
const labels = {open:"Abierta", in_progress:"En progreso", resolved:"Resuelta", discarded:"Descartada", customer:"Cliente", branch:"Sede", internal:"Interno", service:"Servicio", product_quality:"Calidad de producto", payment:"Pago", technology:"Tecnología", inventory:"Inventario", operations:"Operaciones", other:"Otro"};
const branchLabel = branch => branch === "central" ? "Central" : branch.replace("medellin_", "Medellín · ").replace("florida_", "Florida · ").replaceAll("_", " ").replace(/(^| · )\w/g, char => char.toUpperCase());
const $ = selector => document.querySelector(selector);

function fillBranches() { BRANCHES.forEach(branch => [$("#branch"), $("#branchFilter")].forEach(select => { const option = document.createElement("option"); option.value = branch; option.textContent = branchLabel(branch); select.append(option); })); }
function showState(message, retry = false) { const state = $("#listState"); state.innerHTML = `<p>${message}</p>${retry ? '<button class="primary" id="retry">Reintentar</button>' : ""}`; state.classList.remove("hidden"); if (retry) $("#retry").onclick = loadIncidents; }
async function request(path, options) { const response = await fetch(`${API}${path}`, {headers: {"Content-Type":"application/json"}, ...options}); const body = await response.json().catch(() => ({})); if (!response.ok) throw body; return body; }
async function loadIncidents() { showState("Cargando incidencias..."); $("#incidentList").innerHTML = ""; const params = new URLSearchParams(); [["status",$("#statusFilter").value],["origin",$("#originFilter").value],["branch",$("#branchFilter").value]].forEach(([key,value]) => value && params.set(key,value)); try { const incidents = await request(`/incidents?${params}`); $("#listState").classList.add("hidden"); if (!incidents.length) { showState("No hay incidencias con estos filtros."); return; } incidents.forEach(renderIncident); } catch (_) { showState("No pudimos cargar las incidencias. Comprueba tu conexión.", true); } }
function renderIncident(incident) { const item = document.createElement("article"); item.className = "incident"; item.dataset.status = incident.status; item.innerHTML = `<div><h3>${escapeHtml(incident.title)}</h3><p>${escapeHtml(incident.description)}</p><div class="meta"><span class="tag">${labels[incident.category] || incident.category}</span><span>${labels[incident.origin] || incident.origin}</span><span>${branchLabel(incident.branch)}</span><span>${new Date(incident.created_at).toLocaleDateString("es-CO")}</span></div></div><div class="status-control"><select aria-label="Estado de incidencia"><option value="open">Abierta</option><option value="in_progress">En progreso</option><option value="resolved">Resuelta</option><option value="discarded">Descartada</option></select></div>`; const select = item.querySelector("select"); select.value = incident.status; select.onchange = () => changeStatus(incident, select, item); $("#incidentList").append(item); }
async function changeStatus(incident, select, item) { const previous = incident.status; const target = select.value; select.disabled = true; try { const updated = await request(`/incidents/${incident.id}/status`, {method:"PATCH", body:JSON.stringify({status:target})}); incident.status = updated.status; await loadSummary(); } catch (error) { select.value = previous; alert(error.message || "No se pudo actualizar el estado."); } finally { select.disabled = false; item.dataset.status = incident.status; } }
async function loadSummary() { try { const summary = await request("/incidents/summary"); $("#openCount").textContent = summary.by_status.open || 0; $("#progressCount").textContent = summary.by_status.in_progress || 0; $("#resolvedCount").textContent = summary.by_status.resolved || 0; $("#summary .metric strong").textContent = summary.total || 0; $("#summaryDetails").innerHTML = [["Por estado",summary.by_status],["Por categoría",summary.by_category],["Por origen",summary.by_origin],["Por sede",summary.by_branch]].map(([title,values]) => `<div class="summary-card"><h3>${title}</h3>${Object.keys(values).length ? Object.entries(values).map(([key,value]) => `<div class="summary-line"><span>${title === "Por sede" ? branchLabel(key) : labels[key] || key}</span><b>${value}</b></div>`).join("") : '<p class="lead">Sin datos todavía</p>'}</div>`).join(""); } catch (_) { $("#summaryDetails").innerHTML = '<div class="state">El resumen no está disponible ahora. El registro sigue funcionando.</div>'; } }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char])); }
function openModal() { $("#modal").classList.remove("hidden"); $("[name=title]").focus(); }
function closeModal() { $("#modal").classList.add("hidden"); }
$("#newIncident").onclick = openModal; $("#closeModal").onclick = closeModal; $("#refresh").onclick = () => { loadIncidents(); loadSummary(); }; ["#statusFilter","#originFilter","#branchFilter"].forEach(selector => $(selector).onchange = loadIncidents); $("#origin").onchange = event => $("#branchField").classList.toggle("highlight", event.target.value === "branch");
$("#incidentForm").onsubmit = async event => { event.preventDefault(); const form = event.target; form.querySelectorAll(".field-error").forEach(error => error.textContent = ""); $("#formMessage").textContent = ""; const button = $("#submit"); button.disabled = true; button.textContent = "Registrando..."; const data = Object.fromEntries(new FormData(form)); try { await request("/incidents", {method:"POST",body:JSON.stringify(data)}); form.reset(); $("#formMessage").textContent = "Incidencia registrada correctamente."; $("#formMessage").className = "form-message success"; await Promise.all([loadIncidents(),loadSummary()]); } catch (error) { const errors = error.errors || {}; Object.entries(errors).forEach(([field,message]) => { const fieldError = form.elements[field]?.parentElement.querySelector(".field-error"); if (fieldError) fieldError.textContent = message; }); $("#formMessage").textContent = Object.keys(errors).length ? "Revisa los campos marcados." : "No pudimos registrar la incidencia. Inténtalo de nuevo."; } finally { button.disabled = false; button.textContent = "Registrar incidencia"; } };
fillBranches(); loadIncidents(); loadSummary();